### ISSUE TITLE
Scrolling up in the dropdown menu does not work

### ISSUE THREAD

**Issue by Kasalehlia** [raphaelm/c3nav-android#1]
When a dropdown menu is open (e.g. when choosing your origin), trying to scroll up instead triggers a reload within the app and resets the dropdown.
Scrolling down works fine, and if you scroll down a little and don't lift your finger up, scrolling up works.

**Comment by raphaelm** [comment]
I can't reproduce this problem on my device. What device and Android version are you using?

**Comment by Kasalehlia** [comment]
I have a Moto G (falcon) with CyanogenMod 12.1 snapshot (Android 5.1.1)

**Comment by NoMoKeTo** [comment]
Happens also for me now.
