### ISSUE TITLE
Make the app show even when the phone is locked

### ISSUE THREAD

**Issue by raphaelm** [raphaelm/c3nav-android#2]
If we set ``android:showOnLockScreen`` on our activity, as soon as someone locks his phone while using our app, the app will show without the need to unlock the device when the screen is turned back on. This is really useful when you run through a building using your phone for navigation.

**Comment by ligi** [comment]
android:showOnLockScreen is minSDK 17 - but we can use WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED to get this for earlier versions - PR will follow soon
