### ISSUE TITLE
Add Navigation-Intent

### ISSUE THREAD

**Issue by ligi** [raphaelm/c3nav-android#6]
to then be e.g. called from Fahrplan-Apps 

Were is the list of pois btw - doesn't seem to be this one: https://github.com/NoMoKeTo/c3nav/blob/master/src/poi.json

**Comment by raphaelm** [comment]
There is no need for a special intent, the Fahrplan app could just make a normal intent to https://c3nav.de/?d=h1 and the app will be opened.

@NoMoKeTo can you comment on the list of POIs?

**Comment by raphaelm** [comment]
Or did you mean implementing another common intent type? I could only think of ``geo:`` URLs which don't really make sense here.

**Comment by ligi** [comment]
Ah missed the filters - nice - closing

**Comment by NoMoKeTo** [comment]
@ligi The list of POIs can now be found here: https://github.com/NoMoKeTo/c3nav/blob/master/src/projects/32c3/pois.json 
Its also possible to refer to any room or roomgroup. POI-groups are also on its way.

**Comment by ligi** [comment]
thanks!

**Comment by NoMoKeTo** [comment]
I'm now working on referring to direct coordinates (will be needed for positioning anyways)

**Comment by ligi** [comment]
just opened a PR on CampFahrplan to connect it with this app: https://github.com/tuxmobil/CampFahrplan/pull/118

**Comment by NoMoKeTo** [comment]
Awesome! :)
